### ISSUE TITLE
please add support for landscape & desktop view

### ISSUE THREAD

**Issue by schneegecko** [hive-keychain/hive-keychain-mobile#20]
hi, as i figuerd out i cannot click on "confirm" on my samsung tablet if i play in landscape and split screen mode. It seems there are scaling issues. Best wishes

**Comment by schneegecko** [comment]
![Screenshot_20210501-094146_Hive Keychain](https://user-images.githubusercontent.com/55052469/116775140-90a1bb00-aa61-11eb-9201-a227d4010c3a.jpg)

**Comment by stoodkev** [comment]
Hi! I realize I forgot to answer you, sorry about that.
The thing is that we do not support these features at the time, it s supposed to always be locked in portrait mode. 
I'm working on adding landscape for browser screen only.

**Comment by 4Ykw** [comment]
Yeah, for me it would add some extra "easiness" because the screen is not too big. So definitely as a future feature would be nice.

Any code reason for the decision on making it always locked in the portrait mode? (besides work of course)

**Comment by inertia186** [comment]
I very much appreciate that Hive Keychain is not following Metamask too closely.  When using both Hive Keychain and Metamask on an iPad in landscape mode, it's somewhat awkward.

However, the browser of Hive Keychain is much better than Metamask, which is great.

But I agree that a bit more work on landscape would be very much appreciated.

For instance, once you enter landscape mode in the browser, it's difficult to navigate from the three dots.
