### ISSUE TITLE
[BUG] "Private Key should be buffer"

### ISSUE THREAD

**Issue by F041** [hive-keychain/hive-keychain-mobile#38]
**To Reproduce**
1. Go to Hive wallet or click tokens on the Hive keychain app
2. Click on transfer
3. Accept the transaction popup on the app

**Expected behavior**
hive sent to the designated address

**Comment by stoodkev** [comment]
Which wallet?
In the in-App browser or through HiveAuth ?
Do you have your private active key in your Keychain wallet?

**Comment by F041** [comment]
> Which wallet? In the in-App browser or through HiveAuth ? Do you have your private active key in your Keychain wallet?

I updated the previous.

I do have the private key there. I tried pasted also the active one, but I don't see it

**Comment by stoodkev** [comment]
> I tried pasted also the active one, but I don't see it

What do you mean you don't see it? If in Account management you don't see the active key, transfers and such cannot work. You will need to import it.

Just tested both transfers and Hive Engine ops, they seem to work fine.

**Comment by F041** [comment]
![Screenshot_20220629-174952](https://user-images.githubusercontent.com/19621180/176480556-f4c259a0-29e8-490b-9a16-3457113cd72f.png)
How do I import it?

**Comment by stoodkev** [comment]
just copy paste your active key, you should have all your different keys
from the time you created your account

**Comment by F041** [comment]
I made an attempt I tried already, and now I can see it. I have no idea how you could reproduce it.
